### ISSUE TITLE
Lack definition of conv1x1 in resnet_encoder.py class GlobalEncoder

### ISSUE THREAD

**Issue by SheffieldCao** [wencheng256/BRNet#1]
Hello. Thank you for your great work. I am reading your code and find there is no definition of the function `conv1x1` in `resnet_encoder.py`. I saw that you are referring the resnet code from https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py. The original code of pytorch has a function `conv1x1` in that file. Did you forget to add this part ❓ Thank you.

**Comment by wencheng256** [comment]
Please refer to another issue
